@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 23 13:12:39 +0530 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim new_7_behav -key {Behavioral:sim_1:Functional:new_7} -tclbatch new_7.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -view C:/my pc/desktop/matlab/exp8_io/hdl_prj/vivado_prj/new_7_behav.wcfg -log simulate.log"
call xsim  new_7_behav -key {Behavioral:sim_1:Functional:new_7} -tclbatch new_7.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -view C:/my pc/desktop/matlab/exp8_io/hdl_prj/vivado_prj/new_7_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
