// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\new_7\FIR_system_new.v
// Created: 2025-06-24 11:26:22
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIR_system_new
// Source Path: new_7/main _module_new/FIR_system_new
// Hierarchy Level: 2
// Model version: 1.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIR_system_new
          (clk,
           reset_x,
           enb,
           o1_re,
           o1_im,
           output_re,
           output_im);


  input   clk;
  input   reset_x;
  input   enb;
  input   signed [7:0] o1_re;  // sfix8_En6
  input   signed [7:0] o1_im;  // sfix8_En6
  output  signed [7:0] output_re;  // sfix8_En6
  output  signed [7:0] output_im;  // sfix8_En6


  wire signed [7:0] Constant8_out1;  // sfix8_En6
  wire signed [7:0] Constant13_out1;  // sfix8_En6
  wire signed [7:0] Constant9_out1;  // sfix8_En6
  wire signed [7:0] Constant14_out1;  // sfix8_En6
  wire signed [7:0] Constant10_out1;  // sfix8_En6
  wire signed [7:0] Constant15_out1;  // sfix8_En6
  wire signed [7:0] Constant11_out1;  // sfix8_En6
  wire signed [7:0] Constant16_out1;  // sfix8_En6
  wire signed [7:0] Constant12_out1;  // sfix8_En6
  wire signed [7:0] Constant17_out1;  // sfix8_En6
  wire signed [7:0] Constant1_out1;  // sfix8_En6
  wire signed [7:0] Constant18_out1;  // sfix8_En6
  wire signed [7:0] Constant2_out1;  // sfix8_En6
  wire signed [7:0] Constant19_out1;  // sfix8_En6
  wire signed [7:0] Constant3_out1;  // sfix8_En6
  wire signed [7:0] Constant20_out1;  // sfix8_En6
  wire signed [7:0] Constant4_out1;  // sfix8_En6
  wire signed [7:0] Constant21_out1;  // sfix8_En6
  wire signed [7:0] Constant5_out1;  // sfix8_En6
  wire signed [7:0] Constant22_out1;  // sfix8_En6
  wire signed [7:0] Constant6_out1;  // sfix8_En6
  wire signed [7:0] Constant23_out1;  // sfix8_En6
  wire signed [7:0] Constant7_out1;  // sfix8_En6
  wire signed [7:0] Constant24_out1;  // sfix8_En6
  wire signed [7:0] Subsystem_out1_re;  // sfix8_En6
  wire signed [7:0] Subsystem_out1_im;  // sfix8_En6


  assign Constant8_out1 = 8'sb00001110;

  assign Constant13_out1 = 8'sb00000000;

  assign Constant9_out1 = 8'sb11100010;

  assign Constant14_out1 = 8'sb00000000;

  assign Constant10_out1 = 8'sb00001111;

  assign Constant15_out1 = 8'sb00000000;

  assign Constant11_out1 = 8'sb00001010;

  assign Constant16_out1 = 8'sb00000000;

  assign Constant12_out1 = 8'sb11110111;

  assign Constant17_out1 = 8'sb00000000;

  assign Constant1_out1 = 8'sb11111110;

  assign Constant18_out1 = 8'sb00000000;

  assign Constant2_out1 = 8'sb00000101;

  assign Constant19_out1 = 8'sb00000000;

  assign Constant3_out1 = 8'sb00000000;

  assign Constant20_out1 = 8'sb00000000;

  assign Constant4_out1 = 8'sb11111110;

  assign Constant21_out1 = 8'sb00000000;

  assign Constant5_out1 = 8'sb00000001;

  assign Constant22_out1 = 8'sb00000000;

  assign Constant6_out1 = 8'sb00000001;

  assign Constant23_out1 = 8'sb00000000;

  assign Constant7_out1 = 8'sb00000000;

  assign Constant24_out1 = 8'sb00000000;

  Subsystem u_Subsystem (.clk(clk),
                         .reset_x(reset_x),
                         .enb(enb),
                         .h0_re(Constant8_out1),  // sfix8_En6
                         .h0_im(Constant13_out1),  // sfix8_En6
                         .h1_re(Constant9_out1),  // sfix8_En6
                         .h1_im(Constant14_out1),  // sfix8_En6
                         .h2_re(Constant10_out1),  // sfix8_En6
                         .h2_im(Constant15_out1),  // sfix8_En6
                         .h3_re(Constant11_out1),  // sfix8_En6
                         .h3_im(Constant16_out1),  // sfix8_En6
                         .h4_re(Constant12_out1),  // sfix8_En6
                         .h4_im(Constant17_out1),  // sfix8_En6
                         .h5_re(Constant1_out1),  // sfix8_En6
                         .h5_im(Constant18_out1),  // sfix8_En6
                         .h6_re(Constant2_out1),  // sfix8_En6
                         .h6_im(Constant19_out1),  // sfix8_En6
                         .h7_re(Constant3_out1),  // sfix8_En6
                         .h7_im(Constant20_out1),  // sfix8_En6
                         .h8_re(Constant4_out1),  // sfix8_En6
                         .h8_im(Constant21_out1),  // sfix8_En6
                         .h9_re(Constant5_out1),  // sfix8_En6
                         .h9_im(Constant22_out1),  // sfix8_En6
                         .h10_re(Constant6_out1),  // sfix8_En6
                         .h10_im(Constant23_out1),  // sfix8_En6
                         .h11_re(Constant7_out1),  // sfix8_En6
                         .h11_im(Constant24_out1),  // sfix8_En6
                         .input_re(o1_re),  // sfix8_En6
                         .input_im(o1_im),  // sfix8_En6
                         .output1_re(Subsystem_out1_re),  // sfix8_En6
                         .output1_im(Subsystem_out1_im)  // sfix8_En6
                         );

  assign output_re = Subsystem_out1_re;

  assign output_im = Subsystem_out1_im;

endmodule  // FIR_system_new

